/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}
open class Tag(val name: String) {
		private val children = mutableListOf<Tag>()
		protected fun<T : Tag> doInit(child: T, init: T.() -> Unit) {
				child.init()
				children.add(child)
		}
		override fun toString() = "<$name>${children.joinToString("")}</$name>"
}

fun table(init: TABLE.() -> Unit) = TABLE().apply(init)
class TABLE : Tag("table") {
		fun tr(init: TR.() -> Unit) = doInit(TR(), init)
}
class TR: Tag("tr") {
		fun td(init: TD.() -> Unit) = doInit(TD(), init)
}
class TD: Tag("td")
fun createTable() =
		table {
				tr {
						td {}
				}
		}
fun createAnotherTable() =
		table {
				for (i in 1..2) {
						tr {
								td {}
						}
				}
		}
fun main() {
    println(App().greeting)
		println(createTable())
		println(createAnotherTable())
}
